# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0daa75c3fa974c9d861e8f7faef567566db2d52cfd46ff321b2a93f964b37a0f6e10723493420af37cea84e9453bd17d2cdfacadfb0261515415b86056e4103

test:
  secret_key_base: bfc52c22924aaa1c369de73d3156616f7d2aa9fb183a7b0157146e5bab4f47113445d55fe171717bd1ea1bf3f17d71be5aefe520ccb09367e2aee56675ec46a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
